name: "Build and Publish (pre-release)"

on:
    push:
        branches: ["pre-release"]
    workflow_dispatch:

jobs:
    build_and_publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: ./.github/actions/install-nodejs-and-packages

            - name: Build (pre-release)
              id: build
              uses: ./.github/actions/build-pre-release
              with:
                  is_pre_release: true
                  save_artifacts: true
                  push_changes: false
                  tag: false

            - name: Publish to marketplace
              uses: ./.github/actions/publish-to-marketplace
              env:
                  VSCE_PAT: ${{ secrets.VSCE_PAT }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  pre_release: true
